// Real Chromium voice-cycle checks with mocked microphone/audio; no personal recording.
const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,webPreferences:{preload:path.join(__dirname,'test-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 await win.loadFile(path.join(__dirname,'index.html'));await sleep(300);
 const evaluate=code=>win.webContents.executeJavaScript(code);
 const event=async(type,payload)=>{win.webContents.send('jarvis:test-event',{type,payload});await sleep(70);};
 assert.deepEqual(await evaluate('window.jarvis.testState().records'),[]);
 await evaluate(`window.testAudios=[];window.Audio=class{constructor(){this.events={};window.testAudios.push(this);}addEventListener(name,fn){this.events[name]=fn;}play(){this.events.play?.();return Promise.resolve();}pause(){}};true`);
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 assert.deepEqual(await evaluate('window.jarvis.testState().records'),['start']);
 await event('voice.transcript',{text:'Olá Jarvis'});
 assert.deepEqual(await evaluate('window.jarvis.testState().sends'),['Olá Jarvis']);
 await event('message.complete',{text:'Olá! Como posso ajudar?',status:'complete'});
 assert.equal(await evaluate('document.body.dataset.state'),'speaking');
 assert.equal((await evaluate('window.jarvis.testState().records')).filter(x=>x==='start').length,1);
 await evaluate('window.testAudios[0].events.ended()');await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 assert.equal((await evaluate('window.jarvis.testState().records')).filter(x=>x==='start').length,2);
 await event('voice.status',{state:'transcribing'});
 assert.equal(await evaluate("document.getElementById('mic').disabled"),false);
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 await event('voice.transcript',{text:'Fala atrasada'});
 assert.equal((await evaluate('window.jarvis.testState().sends')).length,1);
 await evaluate("document.getElementById('input').value='quero conversar por voz';document.getElementById('form').requestSubmit()");await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 await evaluate("document.getElementById('input').value='Criar projeto';document.getElementById('form').requestSubmit()");await sleep(70);
 await evaluate('window.testAudios[0].events.error()');assert.equal(await evaluate('document.body.dataset.state'),'processing');
 await event('user.request',{id:'test',method:'approval',params:{command:'<img src=x onerror=alert(1)>',choices:['once','deny']}});
 assert.equal(await evaluate('document.body.dataset.state'),'waiting');assert.equal(await evaluate("!!document.querySelector('#decision img')"),false);
 await event('request.cancel',{id:'test'});assert.equal(await evaluate("document.getElementById('decision').hidden"),true);
 const output=process.env.JARVIS_CHECK_OUTPUT;fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'renderer-resultado.json'),JSON.stringify({microphoneOffAtStartup:true,automaticVoiceSubmit:true,automaticPlayback:true,rearmsAfterPlayback:true,microphonePausedDuringPlayback:true,stopDuringTranscription:true,lateTranscriptNotSent:true,textCommandStartsVoice:true,staleAudioCannotResetTask:true,approvalEscaped:true},null,2));
 win.close();app.quit();
}).catch(error=>{console.error(error.stack);app.exit(1);});