// Real Chromium voice-cycle checks with mocked microphone/audio; no personal recording.
const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
app.setPath('userData',path.join(app.getPath('temp'),'jarvis-renderer-check-'+process.pid));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,webPreferences:{preload:path.join(__dirname,'test-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 win.webContents.on('console-message',event=>console.error('Renderer:',event.message));
 await win.loadFile(path.join(__dirname,'index.html'));await sleep(300);
 const evaluate=code=>win.webContents.executeJavaScript(code);
 const nativeButton=await evaluate("Array.from(document.querySelectorAll('button')).some(x=>x.textContent==='Abrir interface completa do Hermes')");
 assert.ok(nativeButton,'Native interface button missing');
 await evaluate("Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='Abrir interface completa do Hermes').click()");await sleep(70);
 assert.ok(await evaluate("document.getElementById('capabilities-info').textContent.includes('próprias conversas')"));
 const event=async(type,payload)=>{win.webContents.send('jarvis:test-event',{type,payload});await sleep(70);};
 assert.deepEqual(await evaluate('window.jarvis.testState().records'),[]);
 await evaluate("document.getElementById('model-refresh').click()");await sleep(70);
 assert.equal(await evaluate("document.getElementById('model-choice').options.length"),2);
 await evaluate("document.getElementById('model-choice').value='gemini-2.5-flash';document.getElementById('model-apply').click()");await sleep(70);
 assert.deepEqual(await evaluate('window.jarvis.testState().models'),['gemini-2.5-flash']);
 await evaluate("document.getElementById('capabilities-refresh').click()");await sleep(70);
 assert.ok(await evaluate("document.getElementById('capabilities-tools').textContent.includes('read_file')"));
 await evaluate(`window.testAudios=[];window.Audio=class{constructor(){this.events={};window.testAudios.push(this);}addEventListener(name,fn){this.events[name]=fn;}play(){this.events.play?.();return Promise.resolve();}pause(){}};true`);
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 assert.deepEqual(await evaluate('window.jarvis.testState().records'),['start']);
 await evaluate("document.getElementById('model-apply').click()");await sleep(70);
 assert.equal((await evaluate('window.jarvis.testState().models')).length,1,'Model switch during voice must be blocked');
 await event('voice.transcript',{text:'Olá Jarvis'});
 assert.deepEqual(await evaluate('window.jarvis.testState().sends'),['Olá Jarvis']);
 await event('message.complete',{text:'Olá! Como posso ajudar?',status:'complete'});
 assert.equal(await evaluate('document.body.dataset.state'),'speaking');
 assert.equal((await evaluate('window.jarvis.testState().records')).filter(x=>x==='start').length,1);
 await evaluate('window.testAudios[0].events.ended()');await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 assert.equal((await evaluate('window.jarvis.testState().records')).filter(x=>x==='start').length,2);
 await event('voice.status',{state:'transcribing'});
 assert.equal(await evaluate("document.getElementById('mic').disabled"),false);
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 await event('voice.transcript',{text:'Fala atrasada'});
 assert.equal((await evaluate('window.jarvis.testState().sends')).length,1);
 assert.equal(await evaluate("document.getElementById('input').value"),'');
 await evaluate("document.getElementById('input').value='quero conversar por voz';document.getElementById('form').requestSubmit()");await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 await evaluate("document.getElementById('mic').click()");await sleep(70);
 await evaluate("document.getElementById('input').value='Criar projeto';document.getElementById('form').requestSubmit()");await sleep(70);
 await evaluate('window.testAudios[0].events.error()');assert.equal(await evaluate('document.body.dataset.state'),'processing');
 await event('user.request',{id:'test',method:'approval',params:{command:'<img src=x onerror=alert(1)>',choices:['once','deny']}});
 assert.equal(await evaluate('document.body.dataset.state'),'waiting');assert.equal(await evaluate("!!document.querySelector('#decision img')"),false);
 await event('request.cancel',{id:'test'});assert.equal(await evaluate("document.getElementById('decision').hidden"),true);

 await event('message.complete',{text:'Projeto pronto',status:'complete'});
 await evaluate("document.getElementById('input').value='Primeira';document.getElementById('form').requestSubmit()");
 assert.equal(await evaluate("document.getElementById('input').disabled"),false);
 await evaluate("document.getElementById('input').focus();document.getElementById('input').value='Segunda';document.getElementById('form').requestSubmit()");
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Primeira');
 assert.equal(await evaluate("document.querySelectorAll('#queue .queued').length"),1);
 await event('message.complete',{text:'Primeira pronta',status:'complete'});await sleep(80);
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Segunda');
 await evaluate("document.getElementById('input').value='Terceira';document.getElementById('form').requestSubmit();document.querySelector('#queue button').click()");await sleep(80);
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Segunda');
 await event('message.complete',{status:'interrupted'});await sleep(80);
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Terceira');
 await evaluate("document.getElementById('input').value='Rascunho';document.getElementById('form').requestSubmit();document.querySelectorAll('#queue button')[1].click()");
 assert.equal(await evaluate("document.getElementById('input').value"),'Rascunho');
 assert.equal(await evaluate("document.querySelectorAll('#queue .queued').length"),0);
 await evaluate("document.getElementById('form').requestSubmit()");
 await event('connection.error',{});
 assert.equal(await evaluate("document.getElementById('input').disabled"),false);
 assert.equal(await evaluate("document.querySelectorAll('#queue .queued').length"),1);

 win.setSize(720,600);await sleep(100);
 await evaluate("document.getElementById('tasks-toggle').click();document.getElementById('system-toggle').click()");
 assert.equal(await evaluate("document.getElementById('tasks').hidden"),true);
 const overlaps=await evaluate("(()=>{const p=document.getElementById('system').getBoundingClientRect(),c=document.querySelector('.composer-wrap').getBoundingClientRect();return !(p.right<=c.left||p.left>=c.right||p.bottom<=c.top||p.top>=c.bottom);})()");
 assert.equal(overlaps,false,'Context panel covers composer');
 await evaluate("document.getElementById('calendar-toggle').click()");await sleep(70);
 assert.equal(await evaluate("document.getElementById('system').hidden"),true);
 assert.equal(await evaluate("document.querySelector('#calendar-items img')"),null);
 assert.ok(await evaluate("document.getElementById('calendar-items').textContent.includes('01/01/2099')"));
 // Native transcription can arrive before the start RPC reply; it must submit once.
 await evaluate("document.getElementById('reconnect').click()");await sleep(70);
 await evaluate("document.querySelectorAll('#queue .queued button:last-child').forEach(button=>button.click())");
 await evaluate("window.jarvis.deferStart();document.getElementById('mic').click()");await sleep(40);
 await event('voice.status',{state:'transcribing'});
 await event('voice.transcript',{text:'Pedido antes da confirmação'});
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Pedido antes da confirmação');
 await evaluate('window.jarvis.resolveStart()');await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'processing');
 await event('message.complete',{status:'error',error:'Modelo temporariamente indisponível'});
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 await event('voice.transcript',{no_speech_limit:true});
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 await event('voice.transcript',{text:'Nova pergunta após falha'});
 assert.equal((await evaluate('window.jarvis.testState().sends')).at(-1),'Nova pergunta após falha');
 await event('error',{message:'Falha temporária do modelo'});
 await sleep(70);assert.equal(await evaluate('document.body.dataset.state'),'listening');
 await evaluate('window.jarvis.failNextSend()');
 await event('voice.transcript',{text:'Pedido com falha de envio'});await sleep(70);
 assert.equal(await evaluate('document.body.dataset.state'),'listening');
 assert.ok(await evaluate("document.getElementById('queue').textContent.includes('Pedido com falha de envio')"));
 await evaluate("document.getElementById('mic').click()");
 await event('error',{message:'Gemini HTTP 429 RESOURCE_EXHAUSTED. Enable billing on your project.'});
 const failureText=await evaluate("document.querySelector('#messages .assistant:last-child').textContent");
 assert.ok(failureText.includes('cota gratuita'));assert.ok(!failureText.includes('Enable billing'));
 const output=process.env.JARVIS_CHECK_OUTPUT;fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'compacto.png'),(await win.webContents.capturePage()).toPNG());fs.writeFileSync(path.join(output,'renderer-resultado.json'),JSON.stringify({microphoneOffAtStartup:true,automaticVoiceSubmit:true,automaticPlayback:true,rearmsAfterPlayback:true,microphonePausedDuringPlayback:true,stopDuringTranscription:true,lateTranscriptNotSent:true,textCommandStartsVoice:true,staleAudioCannotResetTask:true,approvalEscaped:true,inputAvailableDuringTask:true,queuedSendSerialized:true,interruptWaitsForCompletion:true,queueEditing:true,draftSurvivesDisconnect:true,compactPanelsDoNotOverlapComposer:true,calendarLiveResultsRenderedSafely:true,earlyTranscriptSubmittedOnce:true,lateTranscriptIgnoredAfterStop:true,silenceRearmsListening:true,modelFailureRearmsListening:true},null,2));
 win.close();app.quit();
}).catch(error=>{console.error(error.stack);app.exit(1);});
